### ISSUE TITLE
Tennis dataset

### ISSUE THREAD

**Issue by nikky4D** [willi-menapace/PlayableVideoGeneration#1]
Hi, 

Thank you for the paper and the code. It is very interesting. 

I am new to this area so I'm learning about the training method. Could you give me more details on how you setup the Tennis dataset? I would like to expand to my own dataset for video generation.

Thanks

**Comment by willi-menapace** [comment]
Hi Nikky,
for our Tennis dataset we download 2 long tennis matches from Youtube. Since these videos contain many interruptions of the match, we first cut these videos so that they depict only the portions of the match where the players are actually playing, from the service to the realization of the point. These temporal annotations are present in an annotations.csv file in the repository. To respect the single agent assumption of our method we further crop each sequence at the height of the central net.

The videos are then split into a train/validation/test split. For better comparison with other methods, we make every sequence in the test and validation sets of a fixed length, while the training portion is left untouched.

**Comment by nikky4D** [comment]
Thank you very much. This is very helpful. Just a quick clarification, the annotations.csv file for tennis only contains the times you use in training. The bounding box coordinates in the CSV are the cropping locations you use for that sequence. Is that right?

**Comment by willi-menapace** [comment]
Yes, it is correct.

**Comment by nikky4D** [comment]
Nice. Thank you
