### ISSUE TITLE
Question on Variability Embedding

### ISSUE THREAD

**Issue by phillips96** [willi-menapace/PlayableVideoGeneration#2]
Hello,

Thank you for providing the code to this paper! 

I was wondering how you predetermined the value of `K`? It's mentioned that some of the actions were duplicated, so was curious if you saw improvements by lowering `K` to the sort of limit you and I might expect on Breakout for example.

Also, when inferring you mentioned enforcing `vt=0`. Is that also the case when `R` is fed the frame features that have been reconstructed during the mixed training stage?
And does randomly sampling `vt` when testing on something like Tennis produce reasonable outputs? I can understand not using it on Breakout as you don't really want to introduce that non-determinism. 

Thanks again :smile:

**Comment by willi-menapace** [comment]
Hello,
let me clarify these aspects.

With regards to K, inferring the value depends on the dataset. For Atari Breakout the actions are clearly defined (stay, left, right) so we only experimented with K=3. We did not experiment with different values on this dataset. What is most probable is that with lower K, eg K=2 an action will correspond to two of such movements, while the other will capture the remaining one. With higher K, eg K=4 I expect to learn two centroids, close to each other, so one of the actions will probably be captured twice. For the other datasets, the initial estimate for K is based on an educated guess on the actions we think the model should learn. In the case of tennis we could have 5 actions for movement (stay, up, down, left, right) and an action for hitting. Since overestimating K usually results only in the duplication of one of the actions which can easily be discarded at inference time, we decide to pose K=7 to give the model the possibility to learn a seventh action we may not have thought of. I do not expect significant differences if we pose K=8. Using a low K however, such as K=5 would not allow to capture the whole action space, so I expect lower performance.

With regards to vt, we pose them to 0 exclusively when not training. During the whole training process vt is never altered.

We tested random sampling on vt at inference time and we observe that the model can produce different output sequences given the same initial frame and sequence of actions. For simplicity, however, we decide to pose them to 0. You can test this beahvior yourself by calling the function

`model.generate_next(self, observation: torch.Tensor, action: int, noise=False)`

With the noise parameter set to True.

In this regard, you may look at the "Action Variability Embeddings Evaluation" section of the supplementary material where we show that at inference time vt can be used to produce actions that interpolate between the effects of two given actions. Eg. moving diagonally or controlling the movement speed.

Willi

**Comment by phillips96** [comment]
Thank you for explaining, I had assumed as much! I missed the supplementary items so i'll look through those.

Thanks
