### ISSUE TITLE
ResolvePackageNotFound Error

### ISSUE THREAD

**Issue by AVTV64** [willi-menapace/PlayableVideoGeneration#3]
Hello, I'm trying to install using Conda on Windows 10, but when I run "conda env create -f env.yml" it gives me the following error:
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - gstreamer=1.14.0
  - readline=7.0
  - libgcc-ng=9.1.0
  - glib=2.63.1
  - ld_impl_linux-64=2.33.1
  - gmp=6.2.0
  - rhash=1.3.8
  - libedit=3.1.20181209
  - gst-plugins-base=1.14.0
  - ncurses=6.2
  - libstdcxx-ng=9.1.0
  - libuuid=1.0.3
  - expat=2.2.6
  - libgfortran-ng=7.3.0
  - dbus=1.13.12

**Comment by willi-menapace** [comment]
Hello, 
unfortunately the Conda environment that is present on the repository has been tested on Linux only. The issue probably lies in the unavailability of the packages you listed on Windows 10. You could build a new environment starting from a base pytorch installation and installing the packages that are required by the portion of the code you would like to execute. However, since the code has not been tested on Windows, I suggest using a Linux distribution to avoid further issues that may arise during execution.

**Comment by AVTV64** [comment]
> Hello,
> unfortunately the Conda environment that is present on the repository has been tested on Linux only. The issue probably lies in the unavailability of the packages you listed on Windows 10. You could build a new environment starting from a base pytorch installation and installing the packages that are required by the portion of the code you would like to execute. However, since the code has not been tested on Windows, I suggest using a Linux distribution to avoid further issues that may arise during execution.

Thanks. Can you update the code after testing on Windows and/or make a Colab version?
